savvato-software/tribe-app-backend

src/test/java/com/savvato/tribeapp/services/ToBeReviewedServiceImplTest.java
Jonathan requested this change via Slack as we discussed TRIB-61 in an attempt to consistently use the naming convention of "testTestName()" for all unit tests.
=> TRIB 61.1: changes getReviewPhrase() name to testGetReviewPhraseHappyPath()

src/main/java/com/savvato/tribeapp/services/AttributesServiceImpl.java
/api/attributes/{userId} endpoint now returns an optional of the array list of attributeDTOs. It is able to return an empty list, which results in a 200 HTTP response status code when there aren't any attributes for the user.
=> Trib 72: bug fix. Updates get attributes return type to Optional of array list

src/main/java/com/savvato/tribeapp/controllers/AttributesAPIController.java, src/main/java/com/savvato/tribeapp/services/PhraseService.java, src/main/java/com/savvato/tribeapp/services/PhraseServiceImpl.java
Goal: create consistency early on by keeping phrase words in grammatical order
Grammatical order defined: adverb, verb, preposition, noun
Changes made:
- Updates PhraseService and Interface method signatures and properties to grammatical order
- Updates all current calls to these methods in AttributesAPIController to match
=> Trib 95: updates phrase service methods and calls to grammatical order

src/main/resources/db/migration/changelog-202304141047.xml, src/main/resources/db/migration/changelog-202304141049.xml, src/main/resources/db/migration/changelog-202304141125.xml, src/main/resources/db/migration/changelog-202304141136.xml, src/main/resources/db/migration/changelog-202304141143.xml, src/main/resources/db/migration/changelog-202304141226.xml, src/main/resources/db/migration/changelog-202304211617.xml, src/main/resources/db/migration/changelog-master.xml
This migration script updates the column rejected-phrase to rejected_phrase. The previous name was creating access problems in the repo, but this updated name functions as expected. Was able to test adding records in MySQL workbench.
=> TRIB-113: updates database rejected_phrase table column name

src/main/java/com/savvato/tribeapp/repositories/ReviewSubmittingUserRepository.java, src/main/resources/db/migration/changelog-202304251612.xml, src/main/resources/db/migration/changelog-master.xml
I ran into errors trying to save a record to the review_submitting_user table. The errors seemed to be due to the column names userId and toBeReviewedId format. I applied the following fix, and was able to execute my code without error:
- added migration script to update the table column names to user_id and to_be_reviewed_id
- updated changelog master
- searched for any usages and updated reviewSubmittingUserRepository query to use the new column name to_be_reviewed_id
Testing: 
- program compiled and ran
- New field names appeared in MySQL workbench
- Able to insert record
=> Mrsbluerose alter review submitted user table

src/main/java/com/savvato/tribeapp/entities/ReviewSubmittingUserId.java, src/main/java/com/savvato/tribeapp/repositories/ReviewSubmittingUserRepository.java, src/main/java/com/savvato/tribeapp/repositories/ToBeReviewedRepository.java, src/main/java/com/savvato/tribeapp/services/PhraseServiceImpl.java, src/test/java/com/savvato/tribeapp/services/PhraseServiceImplTest.java
When ApplyPhraseToUser is called with a phrase that has not been approved,
check if it is in the to_be_reviewed table
if so, map to user in review_submitting_user table
if not, add to to_be_reviewed table and then map to user
Testing:
- Tested in Postman & MySQL Workbench (passed)
- I can add a unit test, but I am waiting for my previous pull request to be approved (it adds test objects for phrase and words to the abstract test class). Please let me know if you want me to add that test here or open a separate ticket.
=> Trib 74: apply phrase to user when has not been approved

src/main/resources/db/migration/changelog-202305081206.xml, src/main/resources/db/migration/changelog-202305090846.xml, src/main/resources/db/migration/changelog-202305090856.xml, src/main/resources/db/migration/changelog-master.xml
Changes:
- added migration script to changelog master to update review_decision column names to use underscores (no other changes to files. The ReviewDecisionRepository did not have any custom queries with the old field names)
Reviewed all database tables for primary and foreign keys. I did NOT make any changes to these tables (please let me know if any of these do need changed):
1. Did not touch DATABASECHANGELOG and DATABASECHANGELOGLOCK. I assume these are specifically formatted for a reason. DATABASECHANGELOG has an ID column and a DEPLOYMENT_ID column, but neither are specified as primary or foreign key.
2. review_decision has no primary key and three foreign keys (four columns total)
3. review_submitting_user has no primary key and the only two columns are foreign keys
4. …
=> Trib 63: apply database foreign keys and correct column names

src/main/java/com/savvato/tribeapp/entities/ToBeReviewed.java
Previously toBeReviewed's toString() method used to place adverbs at the end of the string that was generated. This pull request places adverbs at start of string, to match expected behavior.
=> TRIB 139 - Fix bug with toBeReviewed's toString() method

pom.xml, src/main/java/com/savvato/tribeapp/config/ConnectWebSocketConfig.java, src/main/java/com/savvato/tribeapp/controllers/ConnectAPIController.java, src/main/java/com/savvato/tribeapp/dto/ConnectIncomingMessageDTO.java, src/main/java/com/savvato/tribeapp/dto/ConnectOutgoingMessageDTO.java, src/main/java/com/savvato/tribeapp/services/ConnectService.java, src/main/java/com/savvato/tribeapp/services/ConnectServiceImpl.java, src/test/java/com/savvato/tribeapp/services/ConnectServiceImplTest.java
A websocket allows the frontend and backend to maintain realtime communication while the connection process is taking place. This pull request adds a Spring websocket in the backend. The ConnectWebSocketConfig file establishes a STOMP endpoint for the frontend to establish a connection to the websocket, and configures a Spring message broker to handle communication on the "/connect/user/queue/specific-user-{username}" destination. The ConnectService, implemented by ConnectServiceImpl, makes changes to the "connections" database table as needed and sends messages to the broker using SimpMessagingTemplate. DTOs are used to provide a uniform structure for incoming and outgoing messages.
=> Implemented websocket to handle connection-related communication between frontend and backend

src/main/java/com/savvato/tribeapp/repositories/ToBeReviewedRepository.java
Previously, the native query used in ToBeReviewedRepository's findNextReviewEligible method used the column name 'hasBeenGroomed'. This was a typo; the real column name is 'has_been_groomed'. This PR implements the correct column name in that native query.
=> TRIB-144: Fix incorrect column name in ToBeReviewedRepository's findNextReviewEligible method

src/main/java/com/savvato/tribeapp/entities/RejectedPhrase.java, src/main/java/com/savvato/tribeapp/repositories/RejectedPhraseRepository.java, src/main/java/com/savvato/tribeapp/services/ToBeReviewedCheckerService.java, src/main/java/com/savvato/tribeapp/services/ToBeReviewedCheckerServiceImpl.java, src/main/resources/db/migration/changelog-202307250728.xml, src/main/resources/db/migration/changelog-master.xml, src/test/java/com/savvato/tribeapp/services/ToBeReviewedCheckerServiceImplTest.java
Previously, ToBeReviewedCheckerServiceImpl's updateTables method contained an additional check to ensure that duplicates weren't inserted into the rejectedPhraseRepository.
```
@Override
public void updateTables(ToBeReviewed tbr, boolean hasMatchingRejectedPhrase, boolean phraseValid) {
if (phraseValid) {
toBeReviewedRepository.setHasBeenGroomedTrue(tbr.getId());
}
else {
**if (!hasMatchingRejectedPhrase) {
RejectedPhrase rp = new RejectedPhrase();
rp.setRejectedPhrase(tbr.toString());
rejectedPhraseRepository.save(rp);
}**
reviewSubmittingUserRepository.deleteByToBeReviewedId(tbr.getId());
toBeReviewedRepository.deleteById(tbr.getId());
}
}
```
This PR eliminates the need for that check by:
-  placing a UNIQUE constraint on the rejected_phrase table's rejected_phrase column,
- …
=> TRIB 140: Refactor for ToBeReviewedCheckerServiceImpl

src/main/java/com/savvato/tribeapp/services/PhraseServiceImpl.java, src/test/java/com/savvato/tribeapp/services/PhraseServiceImplTest.java
- updates applyPhraseToUser to save "nullvalue" in blank adverbs or prepositions in newly added phrases
- updates findPreviouslyApprovedPhraseId comparisons to check for "nullvalue" when building a phrase to search the phrase repo
=> Trib 150: bug fix saves "nullvalue" for blank adverb/preposition

src/main/java/com/savvato/tribeapp/services/AttributesServiceImpl.java, src/main/java/com/savvato/tribeapp/services/PhraseService.java, src/main/java/com/savvato/tribeapp/services/PhraseServiceImpl.java, src/test/java/com/savvato/tribeapp/services/PhraseServiceImplTest.java
- Child issue ticket for TRIB-160
- Updates Phrase Service method getListOfPhraseDTOByUserIdWithoutPlaceholderNullvalue to new name and returns a PhraseDTO with empty strings for adverbs/prepositions that have "nullvalue" placeholders in the database
Testing
- works in postman
- added phrase service test testGetListOfPhraseDTOByUserIdWithoutPlaceholderNullvalueForEmptyStrings
=> Trib 161: AttributesAPIController returns empty string for "nullvalue" placeholder

src/main/java/com/savvato/tribeapp/controllers/ToBeReviewedAPIController.java, src/main/java/com/savvato/tribeapp/services/ToBeReviewedService.java, src/main/java/com/savvato/tribeapp/services/ToBeReviewedServiceImpl.java, src/test/java/com/savvato/tribeapp/services/ToBeReviewedServiceImplTest.java
- updates getReviewPhrase method name to getReviewPhraseWithoutPlaceholderNullvalue
- adds check for any adverb/preposition "nullvalue" placeholders from database and converts them to empty strings before returning to controller
Testing
- adds test to confirm "nullvalue" was replaced
=> Trib 162: updates ToBeReviewed service get review phrase method to return empty strings for any nullvalue placeholders

src/main/java/com/savvato/tribeapp/controllers/UserAPIController.java
(branched off develop)
- removes /changeLostPassword endpoint from User service
- TRIB-188 updates the frontend user service to route to /changePassword
Testing
- ran frontend/backend and verified that the profile page > edit > change password function worked
=> TRIB-189: removes deprecated /changeLostPassword

src/main/java/com/savvato/tribeapp/controllers/AttributesAPIController.java, src/main/java/com/savvato/tribeapp/controllers/annotations/controllers/AttributesAPIController/DeletePhraseFromUser.java, src/main/java/com/savvato/tribeapp/services/UserPhraseService.java, src/main/java/com/savvato/tribeapp/services/UserPhraseServiceImpl.java
- adds new endpoint deletePhraseFromUser to AttributesAPIController
- adds deletePhraseFromUser to UserPhraseService
- adds API Swagger annotation for deletePhraseFromUser
Testing:
- successfully deletes UserPhrase from UserPhrase table with Postman and Swagger UI
Note: AttributesAPIController test class does not exist. Maryam is nearly ready to submit TRIB-130, which may include this new class. I opted to forego creating a possible duplicate class. I can create another ticket specifically for creating a test for the delete endpoint (and creating the test class if needed). Awaiting confirmation from Maryam.
=> Trib 191: add DELETE endpoint to AttributesAPIController

pom.xml, src/main/java/com/savvato/tribeapp/controllers/annotations/config/builders/SchemaBuilder.java, src/main/java/com/savvato/tribeapp/controllers/annotations/config/utils/AnnotationsUtils.java, src/main/java/com/savvato/tribeapp/controllers/annotations/config/utils/RequestAnnotationUtils.java, src/main/java/com/savvato/tribeapp/controllers/annotations/config/utils/ResponseAnnotationUtils.java, src/main/java/com/savvato/tribeapp/services/SMSTextMessageService.java, src/main/java/com/savvato/tribeapp/services/SMSTextMessageServiceImpl.java, src/main/java/com/savvato/tribeapp/services/SystemTimeProviderImpl.java, src/main/java/com/savvato/tribeapp/services/ToBeReviewedCheckerServiceImpl.java, src/test/java/com/savvato/tribeapp/services/ToBeReviewedCheckerServiceImplTest.java
This is part of [TRIB-148: Increase coverage to 50%](https://mockprogrammingjob.atlassian.net/browse/TRIB-148?atlOrigin=eyJpIjoiNjNlMDg3OGU3NTQ0NDkzZWIwNTAxMjBjYmM1YTdhNTUiLCJwIjoiaiJ9).
There are certain services that are implemented in a way that makes it difficult to test them. To achieve better coverage, they need to be tweaked slightly. These are the changes this PR makes:
- Autowire RestTemplate in ToBeReviewedCheckerServiceImpl instead of initializing it inside a method, so it can be mocked
- Separate sendSMS in SMSTextMessageService into 3 methods:
- initialize, which initializes Plivo
- createResponse, which creates the response
- sendSMS, which actually sends the message
This allows Plivo's initialization to be mocked and allows unit tests to be more granular.
- Exclude the …
=> TRIB-148: Improvements necessary for adequate test coverage

src/main/java/com/savvato/tribeapp/controllers/AttributesAPIController.java, src/main/java/com/savvato/tribeapp/controllers/ConnectAPIController.java
This is part of [TRIB-148: Increase coverage to 50%](https://mockprogrammingjob.atlassian.net/browse/TRIB-148?atlOrigin=eyJpIjoiNjNlMDg3OGU3NTQ0NDkzZWIwNTAxMjBjYmM1YTdhNTUiLCJwIjoiaiJ9).
There are certain services that contain faulty logic. For unit tests to pass, they need to be fixed. These are the changes this PR makes:
- Ensure notification sent by AttributesAPIController matches the phrase's approval status (currently, it does the reverse of what the approval status would indicate).
- Add Spring's @RequestBody annotation in ConnectAPIController's connect method, so request body isn't null when a POST request is sent to /api/connect.
=> TRIB-148: Fix faulty logic

.github/workflows/maven-publish.yml
- Split maven build action into two steps, one for installing dependencies and another for running tests & collecting coverage
- Add step for uploading coverage to Codecov
=> Add coverage tracking to CI/CD workflow

src/main/java/com/savvato/tribeapp/controllers/AttributesAPIController.java, src/main/java/com/savvato/tribeapp/controllers/ConnectAPIController.java, src/main/java/com/savvato/tribeapp/entities/NotificationType.java, src/test/java/com/savvato/tribeapp/controllers/AttributesAPITest.java
- adds missing mock beans
- corrects true/false logic for the sendNotification() method in the API Controller
- corrects name of rejected request in Notification types
- also adds missing "@RequestBody" to Connect Controller
Testing
- runs and compiles
- tests run successfully without errors
- program runs in browser
=> Trib 222: bug fix for AttributesAPIController

src/main/java/com/savvato/tribeapp/controllers/AttributesAPIController.java, src/main/java/com/savvato/tribeapp/controllers/annotations/controllers/AttributesAPIController/GetNumberOfUsersWithAttribute.java, src/main/java/com/savvato/tribeapp/repositories/UserPhraseRepository.java, src/main/java/com/savvato/tribeapp/services/AttributesService.java, src/main/java/com/savvato/tribeapp/services/AttributesServiceImpl.java, src/test/java/com/savvato/tribeapp/controllers/AttributesAPITest.java, src/test/java/com/savvato/tribeapp/services/AttributesServiceImplTest.java
Per TRIB-174, we need an endpoint that takes an attribute ID and calculates the number of users that are using that attribute. This PR makes the following changes to put the endpoint into place:
- Add query method to userPhraseRepository that counts the number of users that share the attribute ID
- Add AttributesService method that invokes above method, returning an Optional with the information (or an empty Optional if the database query fails)
- Add GET endpoint at /api/attributes/total/{attributeId} that returns the number of users with a 200 status, or a 400 status depending on the Optional returned by attribtuesService
- Create Swagger annotation for above endpoint to document it
=> TRIB-174: Add endpoint that calculates number of users with a given attribute

src/main/java/com/savvato/tribeapp/controllers/ConnectAPIController.java, src/main/java/com/savvato/tribeapp/controllers/annotations/controllers/ConnectAPIController/SaveCosign.java, src/main/java/com/savvato/tribeapp/controllers/dto/CosignRequest.java, src/main/java/com/savvato/tribeapp/dto/CosignDTO.java, src/main/java/com/savvato/tribeapp/entities/Cosign.java, src/main/java/com/savvato/tribeapp/entities/CosignId.java, src/main/java/com/savvato/tribeapp/repositories/CosignRepository.java, src/main/java/com/savvato/tribeapp/services/CosignService.java, src/main/java/com/savvato/tribeapp/services/CosignServiceImpl.java, src/main/resources/db/migration/changelog-202401110955.xml, src/main/resources/db/migration/changelog-202401111012.xml, src/main/resources/db/migration/changelog-master.xml, src/test/java/com/savvato/tribeapp/controllers/ConnectAPITest.java, src/test/java/com/savvato/tribeapp/services/CosignServiceImplTest.java, src/test/java/com/savvato/tribeapp/services/StorageServiceImplTest.java
Note: I am submitting this early (with questions and incomplete test) to review at our meeting 1/11/2024
Questions: 
1. Do we want a return value from the saveCosign endpoint
2. Do we agree: Cosign endpoint is in Connect Controller, Cosign service and repo are separate
Changes:
- Creates Database table for cosign
- Creates Database table with cosign test data
- Creates Cosign and CosignID entities
- Creates Cosign repository
- Creates Cosign service and Impl with saveCosign method
- Adds saveCosign endpoint to Connect Service and creates CosignRequest DTO and annotation
Testing (WIP)
- Adds Cosign service test for saveCosign (simple, without return values)
- Adds Connect API test  for save Cosign (INCOMPLETE AS OF 1/11)
=> TRIB-210: adds save cosign endpoint

src/main/java/com/savvato/tribeapp/controllers/ConnectAPIController.java, src/main/java/com/savvato/tribeapp/controllers/annotations/controllers/ConnectAPIController/RemoveConnection.java, src/main/java/com/savvato/tribeapp/controllers/dto/ConnectionDeleteRequest.java, src/main/java/com/savvato/tribeapp/controllers/dto/ConnectionRemovalRequest.java, src/main/java/com/savvato/tribeapp/repositories/ConnectionsRepository.java, src/main/java/com/savvato/tribeapp/services/ConnectService.java, src/main/java/com/savvato/tribeapp/services/ConnectServiceImpl.java, src/test/java/com/savvato/tribeapp/controllers/ConnectAPITest.java, src/test/java/com/savvato/tribeapp/services/ConnectServiceImplTest.java
This PR addresses TRIB-105 and creates a DELETE endpoint for removing a connection. The following changes are made:
- Add repository method for deleting connection from connections table in DB
- Create ConnectionRemovalRequestDTO containing the user IDs of the connected users
- Create relevant service method, controller endpoint, endpoint Swagger annotation
- Write relevant unit tests
=> TRIB-105: Create endpoint for removing connection

src/main/java/com/savvato/tribeapp/controllers/ConnectAPIController.java, src/main/java/com/savvato/tribeapp/entities/Connection.java, src/main/resources/db/migration/changelog-202401291541.xml, src/main/resources/db/migration/changelog-master.xml, src/test/java/com/savvato/tribeapp/controllers/ConnectAPITest.java, src/test/java/com/savvato/tribeapp/services/ConnectServiceImplTest.java
- updates database column naming formats for the connections table to correct SQL error at runtime
- updates Connect entity to match new naming conventions
- updates Connect API endpoint from /api/connect/all/{userId} to /api/connect/{userId}/all
Testing
- adds two tests for ConnectAPI get connections endpoint
- adds two tests for ConnectServiceImple getAllConnectionsForAUser
=> TRIB-142: updates ConnectAPI endpoint for getting all connections for a user

src/main/java/com/savvato/tribeapp/entities/Connection.java, src/main/resources/db/migration/changelog-202402070939.xml, src/main/resources/db/migration/changelog-master.xml
- adds DB script to update connections table header created_at to created
- updates connection entity property from createdAt to created
Testing:
- verified all existing tests still run
- created and tested POST connect endpoint in Postman
=> TRIB-181: updates connections table column name to created

pom.xml
As flagged by @mrsbluerose, entities should be excluded from coverage checks since they don't contain business logic. Currently, this is causing PRs like #158 to fail.
=> Exclude entities from coverage checks

src/main/java/com/savvato/tribeapp/entities/Connection.java, src/main/java/com/savvato/tribeapp/entities/ConnectionId.java, src/main/java/com/savvato/tribeapp/repositories/ConnectionsRepository.java, src/main/java/com/savvato/tribeapp/services/ConnectServiceImpl.java, src/main/resources/db/migration/changelog-202401090508.xml, src/main/resources/db/migration/changelog-master.xml, src/test/java/com/savvato/tribeapp/services/ConnectServiceImplTest.java
Currently, invalid connections can be made. These include duplicate connections (either with the same IDs in the same order, or in reversed order), and circular connections (where the requesting user ID is the same as the user ID on the other end of the connection). This PR makes the following fixes:
- Duplicate connections:
- Use a composite primary key in the Connections table consisting of the user ID columns
- Create repository method in ConnectionsRepository to check for existing connections with reversed ID combination
- Circular connections:
- Add check to prevent circular connection
Finally, as per earlier discussion, this PR also uses the Optional `ofNullable` and `orElse` methods to gracefully exit early if no corresponding QR code exists for the requesting user's ID on …
=> TRIB-230: Prevent invalid connections from occurring

src/main/java/com/savvato/tribeapp/controllers/ConnectAPIController.java, src/main/java/com/savvato/tribeapp/services/CosignService.java, src/main/java/com/savvato/tribeapp/services/CosignServiceImpl.java, src/test/java/com/savvato/tribeapp/controllers/ConnectAPITest.java, src/test/java/com/savvato/tribeapp/services/CosignServiceImplTest.java
- updates cosign service saveCosign() return type to Optional<CosignDTO>
- updates Connect API call to cosign service saveCosign() to Optional<CosignDTO>
- adds Connect API return for bad request 403 forbidden
TESTING
Cosign service and Connect API
- updates variable names for clarity (test, mock, expected)
- updates return values to the new Optional<CosignDTO> change
- simplifies assertions with recursive comparison method
- corrects testing values for save cosign happy path to be different ids
- adds save cosign sad path for when IDs are the same
QUESTIONS:
This ticket is a stab in the dark. Please let me know if you want changes to the return values for the ConnectAPI save cosign endpoint.
=> Trib 244: bug fix users may not cosign themselves

.github/workflows/codecov-publish.yml, .github/workflows/maven-publish.yml
This PR adds the CodeCov token and removes the duplicate GitHub coverage collection & upload actions found in `maven-publish.yml`. (The same actions exist in `codecov-publish.yml` already).
=> Add CodeCov token, remove duplicate Github coverage actions

.github/workflows/codecov-publish.yml, .github/workflows/maven-publish.yml
Currently, coverage is being uploaded _after_ the pull request has been merged. This is important because it allows the branch's existing coverage to be compared against the incoming PR's coverage. However, coverage also needs to be uploaded upon the creation of a pull request, so that insufficient coverage can be flagged and PRs with low coverage can be blocked.
=> TRIB-261: Ensure coverage is uploaded on pull requests as well.

src/main/java/com/savvato/tribeapp/controllers/AttributesAPIController.java, src/main/java/com/savvato/tribeapp/controllers/annotations/controllers/AttributesAPIController/ApplyPhraseToUser.java, src/main/java/com/savvato/tribeapp/dto/AttributesApplyPhraseToUserDTO.java, src/main/java/com/savvato/tribeapp/entities/NotificationType.java, src/main/java/com/savvato/tribeapp/services/PhraseService.java, src/main/java/com/savvato/tribeapp/services/PhraseServiceImpl.java, src/main/resources/db/migration/changelog-202309050841.xml, src/main/resources/db/migration/changelog-202410031119.xml, src/main/resources/db/migration/changelog-master.xml, src/test/java/com/savvato/tribeapp/integration/controllers/AttributesAPIIT.java, src/test/java/com/savvato/tribeapp/unit/services/PhraseServiceImplTest.java
- Adds AttiributesApplyPhraseToUserDTO
- Refactors AttributeAPI applyPhraseToUser endpoint to use new DTO
- Refactors PhraseService applyPhraseToUser to use new DTO
- Refactors AttributeAPI sendNotification with a third notification type for in review
- Adds new notification type for in review
- Updates database with new notification type
Testing:
- updated tests with new DTO
- added PhraseService tests for DTO builders (may not be necessary)
- expected results returned in Postman
NOTE: changes data returned to the frontend!
Old implementation:
returned GenericResponseDTO.BooleanMessage
- false: phrase was either rejected or put in toBeReviewed
- true: phrase was applied to user
New implementation:
returns AttributesApplyPhraseToUserDTO with one field set to true and the rest to false.
- …
=> TRIB-289: adds AttributesApplyPhraseToUser DTO and in review notification
