- postman_collection.json
Our postman_collection.json file listed the admin email as "admin@votingapp.com". I updated it to "admin@tribeapp.com".
> Mrsbluerose/postman: updates admin email address

- src/main/java/com/savvato/tribeapp/services/AttributesServiceImpl.java
Removes private final variables and constructor. Autowires repos for verb, noun, adverb, preposition, and regectedNonEnglishWord
> Mrsbluerose/attribute service retool: removes constructor and autowires repos

- src/main/java/com/savvato/tribeapp/controllers/AttributesAPIController.java
- src/main/java/com/savvato/tribeapp/services/AttributesService.java
- src/main/java/com/savvato/tribeapp/services/AttributesServiceImpl.java
- src/main/java/com/savvato/tribeapp/services/PhraseService.java
- src/main/java/com/savvato/tribeapp/services/PhraseServiceImpl.java
* TRIB-33-minor-fixes: changes name of List<PhraseDTO> to list (#48)
* TRIB-33-minor-fixes: changes name of List<PhraseDTO> to list
* TRIB-33-minor-fixes: changes list name to phrases
* TRIB-72: Changes get attributes endpoint to return optional of array list only (#49)
* mrsbluerose/attribute-service-retool: removes private final variables and constructor. Autowires repos for verb, noun, adverb, preposition, regectedNonEnglishWord (#51)
* Trib 81: migrates all phrase related functionality from attribute service to phrase service (#52)
* TRIB-81: autowires phrase service and updates call on api/attributes to use phrase service
* TRIB-81: removes all phrase-related methods and word repositories
* TRIB-81: adds all phrase-related methods previously in attributes service. Also adds …
> Feature/attributes page (#53)

- src/main/java/com/savvato/tribeapp/services/PhraseServiceImpl.java
Changes logger type in phraseService to match SMSChallengeCodeService. Tested calls in postman. Unit tests all passed.
> Mrsbluerose fix logger

- src/main/java/com/savvato/tribeapp/services/PhraseServiceImpl.java
- src/test/java/com/savvato/tribeapp/services/AbstractServiceImplTest.java
- src/test/java/com/savvato/tribeapp/services/PhraseServiceImplTest.java
Test to verify that userPhraseRepository is called once when applyPhraseToUser is called on a phrase that has already been approved.
> Mrsbluerose phrase service test

- src/main/java/com/savvato/tribeapp/services/PhraseServiceImpl.java
updates logger from apache commons to lombok Slf4j
> mrsbluerose-phrase-service-lombok-log

- src/main/java/com/savvato/tribeapp/controllers/NotificationAPIController.java
- src/main/java/com/savvato/tribeapp/dto/NotificationUpdateDTO.java
- src/main/java/com/savvato/tribeapp/services/NotificationService.java
Created new request DTO for updating Notificaiton Status
Add put method in API copntroller
Add methods to check to see if the notification has been read.
- if the notification has been read, repond with 200 and a message stating so.
- if the notification doesn't exist then reponds with 404 Not found
- if the notificaiton has not been read, repond with 200 and a message stating its been updated.
To use the API send a put request to /api/notification with the body containing a JSON with the ID
> TRIB-90: Add API PUT ENDPOINT

- src/main/java/com/savvato/tribeapp/controllers/AttributesAPIController.java
phrase was valid or not. Previously, it either returned TRUE if valide, or BAD_REQUEST.
> ApplyPhraseToUser() returns true or false depending on whether the

- src/main/java/com/savvato/tribeapp/controllers/AttributesAPIController.java
- src/main/java/com/savvato/tribeapp/entities/ToBeReviewed.java
Earlier, the AttributesAPIController class would simply return a True or False ResponseEntity based on phrase/attribute validity. This PR extends the controller's functionality by sending notifications about the phrase's approval or rejection with the notificationService.
> TRIB 138: Send notification for rejected phrase

- src/main/resources/db/migration/changelog-202308220624.xml
- src/main/resources/db/migration/changelog-master.xml
- creates migration script that inserts three test phrases (confirmed all work in Words API)
> TRIB-159: adds test data for to_be_reviewed table

- src/main/java/com/savvato/tribeapp/controllers/NotificationAPIController.java
- src/main/java/com/savvato/tribeapp/controllers/dto/NotificationRequest.java
- src/main/java/com/savvato/tribeapp/dto/NotificationUpdateDTO.java
Modified controller to use body request object.
NotificationRequest.java
repurposed NotificationUpdateDTO to NotificationReqest NotificationUpdateDTO.java
repurposed this DTO for greater purposes.(requestDTO)
> NotificationAPIController.java

- src/main/java/com/savvato/tribeapp/controllers/ReviewDecisionReasonAPIController.java
- src/main/java/com/savvato/tribeapp/dto/ReviewDecisionReasonDTO.java
- src/main/java/com/savvato/tribeapp/repositories/ReviewDecisionReasonRepository.java
- src/main/java/com/savvato/tribeapp/services/ReviewDecisionReasonService.java
- src/main/java/com/savvato/tribeapp/services/ReviewDecisionReasonServiceImpl.java
- src/test/java/com/savvato/tribeapp/controllers/ReviewDecisionReasonAPITest.java
- src/test/java/com/savvato/tribeapp/services/ReviewDecisionReasonServiceImplTest.java
- Creates a ReviewDecisionReasons (RDR) DTO
- Updates RDR repository with a findAll method
- Creates a RDR service with getReviewDecisionReasons()
- Creates a RDR API Controller
Testing:
- returns expected results in Postman
- created happy/sad path tests for service
- created happy path test for api
> Trib 166: creates endpoint for ReviewDecisionReasons

- src/main/resources/db/migration/changelog-202309141950.xml
- src/main/resources/db/migration/changelog-master.xml
- adds migration script to correct error with prepositions listed as nouns in ToBeReviewed test data
> TRIB-180: fixes bug with prepositions and nouns

- src/main/java/com/savvato/tribeapp/controllers/ToBeReviewedAPIController.java
- src/main/java/com/savvato/tribeapp/dto/ToBeReviewedDTO.java
- src/main/java/com/savvato/tribeapp/repositories/ToBeReviewedRepository.java
- src/main/java/com/savvato/tribeapp/services/ToBeReviewedService.java
- src/main/java/com/savvato/tribeapp/services/ToBeReviewedServiceImpl.java
- src/test/java/com/savvato/tribeapp/services/ToBeReviewedServiceImplTest.java
- creates ToBeReviewedDTO
- updates ToBeReviewed Service/Impl getReviewPhrase() method to return DTO
- updates API Controller endpoint getPhrase() to get DTO
- updates ToBeReviewed Service Tests to work with DTO
- error fix: updates ToBeReviewed Repo to return one result
Testing
- tests execute successfully
- Postman query returns expected phrase
> Trib 178: updates ToBeReviewedAPIController to return DTO

- src/main/java/com/savvato/tribeapp/controllers/PermissionsAPIController.java
- src/main/java/com/savvato/tribeapp/dto/UserDTO.java
- src/main/java/com/savvato/tribeapp/services/UserService.java
- src/main/java/com/savvato/tribeapp/services/UserServiceImpl.java
- src/test/java/com/savvato/tribeapp/services/AbstractServiceImplTest.java
- src/test/java/com/savvato/tribeapp/services/UserServiceImplTest.java
- adds a User DTO
- updates the user service/Impl getAll() method to return a list of UserDTO
- updates PermissionsAPIController /users endpoint to get an Iterable of UserDTO
- adds a User Service test for getAll()
- updates Abstract test data for User1 and User2 to set their respective Created and LastUpdated dates
Testing:
- User service test succeeds
- Postman call to permissions/users endpoint returns a list of the 6 test users currently in our database
> Trib 182: updates PermissionsAPIController /users endpoint to return Iterable of UserDTO

- src/main/java/com/savvato/tribeapp/controllers/PermissionsAPIController.java
- src/main/java/com/savvato/tribeapp/dto/UserRoleDTO.java
- src/main/java/com/savvato/tribeapp/services/UserRoleService.java
- src/main/java/com/savvato/tribeapp/services/UserRoleServiceImpl.java
- src/test/java/com/savvato/tribeapp/services/UserRoleImplTest.java
- creates a UserRole DTO class
- updates UserRoleService/Impl getRoles() method to return a list of UserRoleDTOs
- updates the PermissionsAPI /user-roles-list endpoint to get an Iterable of UserRoleDTOs
Testing
- created UserRoleServiceImple test for getRoles() to verify return of list as DTOs
- Postman api call returns existing roles listed in database
> Trib 183: updates PermissionsAPI /user-roles-list to return list of DTOs

- src/main/java/com/savvato/tribeapp/dto/UserDTO.java
- src/main/java/com/savvato/tribeapp/services/UserServiceImpl.java
- src/test/java/com/savvato/tribeapp/services/UserServiceImplTest.java
(branched off develop)
- adds id property to UserDTO
- updates all instances where UserDTO is built with id property:
UserServiceImpl  getAllUsers()
UserServiceImplTest  testGetAllUsersFindsListOfTwoTestUsers()
Testing:
- existing UserService tests all successful
- Postman returns a list of users with ids for /permissions/users endpoint
> Trib 186: updates UserDTO with id property

- src/main/java/com/savvato/tribeapp/controllers/UserAPIController.java
- src/main/java/com/savvato/tribeapp/services/UserService.java
- src/main/java/com/savvato/tribeapp/services/UserServiceImpl.java
- src/test/java/com/savvato/tribeapp/services/UserServiceImplTest.java
(branched off develop)
- updates UserService change password method to return UserDTO
- creates a UserService test for changePassword()
Testing:
- all user service tests succeed
- Postman endpoint able to change password
> TRIB-185: updates user API /changePassword to use UserDTO

- src/main/java/com/savvato/tribeapp/dto/UserDTO.java
- src/main/java/com/savvato/tribeapp/services/UserServiceImpl.java
- src/test/java/com/savvato/tribeapp/services/UserServiceImplTest.java
(branched off develop)
- adds roles to userDTO
- updates user service getUserDTO with roles property
- updates user service tests to check for user roles
Testing:
- user service tests run successfully
- when running the frontend, the user roles display on page when users with roles are clicked
> Trib 187: bug fix. adds user roles to userDTO

- src/main/java/com/savvato/tribeapp/controllers/AttributesAPIController.java
- src/main/java/com/savvato/tribeapp/controllers/annotations/controllers/AttributesAPIController/GetUserPhrasesToBeReviewed.java
- src/main/java/com/savvato/tribeapp/dto/ToBeReviewedDTO.java
- src/main/java/com/savvato/tribeapp/repositories/ReviewSubmittingUserRepository.java
- src/main/java/com/savvato/tribeapp/services/ReviewSubmittingUserService.java
- src/main/java/com/savvato/tribeapp/services/ReviewSubmittingUserServiceImpl.java
- src/main/java/com/savvato/tribeapp/services/ToBeReviewedServiceImpl.java
- src/test/java/com/savvato/tribeapp/services/ReviewSubmittingUserServiceImplTest.java
- src/test/java/com/savvato/tribeapp/services/ToBeReviewedServiceImplTest.java
- creates a ReviewSubmittingUserService
- adds find by userId method to ReviewSubmittingUser Repository
- updates ToBeReviewedDTO with id field and updates all implementations
- adds getUserPhrasesToBeReviewed to AttributesAPIController (endpoint: /api/attributes/in-review/{userId}
- adds AttributesAPI annotation class for method
- adds ReviewSubmittingUserService test class and method to test getting list of DTOs
Testing:
- returns expected results in Postman and Swagger UI
- ReviewSubmittingUserService test class runs successfully
> TRIB-177: adds attributes page endpoint to get user phrases to be reviewed

- src/main/resources/db/migration/changelog-202311141812.xml
- src/main/resources/db/migration/changelog-master.xml
Currently, we need some extra test users. This PR creates a migration script for adding 10 users, all of whose accounts are enabled. These users all have accountholder privileges and the same password as the other test users.
> TRIB-203: Create migration script for adding 10 new test users

- src/main/java/com/savvato/tribeapp/controllers/ConnectAPIController.java
- src/main/java/com/savvato/tribeapp/controllers/annotations/controllers/ConnectAPIController/DeleteCosign.java
- src/main/java/com/savvato/tribeapp/services/CosignService.java
- src/main/java/com/savvato/tribeapp/services/CosignServiceImpl.java
- src/test/java/com/savvato/tribeapp/controllers/ConnectAPITest.java
- src/test/java/com/savvato/tribeapp/services/CosignServiceImplTest.java
- adds deleteCosign endpoint to connect API
- adds deleteCosign method to cosign service
Testing:
- adds test for connect API deleteCosign endpoing
- adds tests for cosign service deleteCosign for when a cosign exists and when it does not
> TRIB-211: adds connect endpoint to delete cosign

- src/main/java/com/savvato/tribeapp/controllers/ConnectAPIController.java
- src/test/java/com/savvato/tribeapp/controllers/ConnectAPITest.java
- returns result of connect service save connection instead of using if statement that returns true/false
Testing:
Added to existing testing a test for when the save method returns false
> TRIB-202: refactors ConnectAPI connect() method with fewer lines of code

- src/main/java/com/savvato/tribeapp/controllers/ConnectAPIController.java
- src/test/java/com/savvato/tribeapp/controllers/ConnectAPITest.java
- refactors connect endpoint to simplify return statements
- adds connect sad path test
> TRIB-240: refactors connectAPI connect endpoint

- src/main/java/com/savvato/tribeapp/controllers/ConnectAPIController.java
- src/main/java/com/savvato/tribeapp/controllers/annotations/controllers/ConnectAPIController/GetAllCosignsForUser.java
- src/main/java/com/savvato/tribeapp/controllers/annotations/controllers/ConnectAPIController/GetCosignersForUserAttribute.java
- src/main/java/com/savvato/tribeapp/dto/CosignDTO.java
- src/main/java/com/savvato/tribeapp/dto/CosignsForUserDTO.java
- src/main/java/com/savvato/tribeapp/dto/UserNameDTO.java
- src/main/java/com/savvato/tribeapp/dto/UsernameDTO.java
- src/main/java/com/savvato/tribeapp/repositories/CosignRepository.java
- src/main/java/com/savvato/tribeapp/services/CosignService.java
- src/main/java/com/savvato/tribeapp/services/CosignServiceImpl.java
- src/main/java/com/savvato/tribeapp/services/UserService.java
- src/main/java/com/savvato/tribeapp/services/UserServiceImpl.java
- src/test/java/com/savvato/tribeapp/controllers/ConnectAPITest.java
- src/test/java/com/savvato/tribeapp/services/CosignServiceImplTest.java
- src/test/java/com/savvato/tribeapp/services/UserServiceImplTest.java
Part 1: endpoint to return list of users that cosigned a specified attribute (phrase) for a user
- Creates UsernameDTO with just id and name
- Creates cosign repo method findCosignersByUserIdReceivingAndPhraseId
- Creates cosign service method getCosignersForUserAttribute
- Creates ConnectAPI endpoint getCosignersForUserAttribute
Part 2: endpoint to return a list of all attributes (phrases) cosigned to a user and a list of all users that cosigned each attribute
- Creates cosigns for user DTO
- Creates cosign repo method findAllByUserIdReceiving
- Creates cosign service getAllCosignsForUser
- Creates ConnectAPI endpoint getAllCosignersForUser
- Creates user service getUsernameDTO to build username DTOs
Testing
- Created tests for new methods in cosign service
- Created tests for new method …
> TRIB-236: adds ConnectAPI endpoints to get all cosigners for user and all cosigners for a given attribute
